"""empty message

Revision ID: 2fdd3454780a
Revises: fe41544d4ee5
Create Date: 2022-06-29 16:05:47.179620

"""
from alembic import op
import sqlalchemy as sa

from api import SQL_INIT_FILE
from extras import get_inserts_from_files


# revision identifiers, used by Alembic.
revision = '2fdd3454780a'
down_revision = 'fe41544d4ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    buildings_table = op.create_table('buildings',
    sa.Column('IDKadastr', sa.Integer(), nullable=False),
    sa.Column('BuildingName', sa.String(length=60), nullable=True),
    sa.Column('Land', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Address', sa.String(length=250), nullable=False),
    sa.Column('Year', sa.SmallInteger(), nullable=False),
    sa.Column('Wear', sa.SmallInteger(), nullable=False),
    sa.Column('Flow', sa.SmallInteger(), nullable=False),
    sa.Column('Picture', sa.String(length=250), nullable=True),
    sa.Column('Comment', sa.Text(), nullable=True),
    sa.Column('MaterialID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MaterialID'], ['materials.IDMaterial'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('IDKadastr')
    )
    # ### end Alembic commands ###
    inserts = get_inserts_from_files(SQL_INIT_FILE)
    op.bulk_insert(
        buildings_table,
        inserts[buildings_table.name]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    # ### end Alembic commands ###
