"""add unit

Revision ID: 7b93302a52a7
Revises: e632022ba33e
Create Date: 2022-07-02 11:06:57.512512

"""
from alembic import op
import sqlalchemy as sa

from api import SQL_INIT_FILE
from extras import get_inserts_from_files


# revision identifiers, used by Alembic.
revision = '7b93302a52a7'
down_revision = 'e632022ba33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    units_table = op.create_table('units',
    sa.Column('IDUnit', sa.Integer(), nullable=False),
    sa.Column('UnitName', sa.String(length=60), nullable=False),
    sa.Column('DateStart', sa.Date(), nullable=False),
    sa.Column('Cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('CostYear', sa.SmallInteger(), nullable=True),
    sa.Column('CostAfter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Period', sa.SmallInteger(), nullable=False),
    sa.Column('HallID', sa.Integer(), nullable=True),
    sa.Column('ChiefID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChiefID'], ['chiefs.IDChief'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['HallID'], ['halls.IDHall'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('IDUnit')
    )
    # ### end Alembic commands ###
    inserts = get_inserts_from_files(SQL_INIT_FILE)
    op.bulk_insert(
        units_table,
        inserts[units_table.name]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
