"""Initial migration.

Revision ID: abf69c84f53f
Revises: 
Create Date: 2022-06-27 12:46:23.845732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf69c84f53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('IDMaterial', sa.Integer(), nullable=False),
    sa.Column('Material', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('IDMaterial'),
    sa.UniqueConstraint('Material')
    )
    op.create_table('targets',
    sa.Column('IDTarget', sa.Integer(), nullable=False),
    sa.Column('Target', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('IDTarget'),
    sa.UniqueConstraint('Target')
    )
    op.create_table('users',
    sa.Column('IDUser', sa.Integer(), nullable=False),
    sa.Column('Login', sa.String(length=32), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('IDUser'),
    sa.UniqueConstraint('Login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('targets')
    op.drop_table('materials')
    # ### end Alembic commands ###
