"""add chief

Revision ID: e632022ba33e
Revises: 300df97c6b14
Create Date: 2022-07-02 09:44:27.132305

"""
from alembic import op
import sqlalchemy as sa

from api import SQL_INIT_FILE
from extras import get_inserts_from_files


# revision identifiers, used by Alembic.
revision = 'e632022ba33e'
down_revision = '300df97c6b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    chief_table = op.create_table('chiefs',
    sa.Column('IDChief', sa.Integer(), nullable=False),
    sa.Column('Chief', sa.String(length=60), nullable=False),
    sa.Column('AddressChief', sa.String(length=120), nullable=False),
    sa.Column('Experience', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('IDChief')
    )
    # ### end Alembic commands ###
    inserts = get_inserts_from_files(SQL_INIT_FILE)
    op.bulk_insert(
        chief_table,
        inserts[chief_table.name]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chiefs')
    # ### end Alembic commands ###
