"""empty message

Revision ID: fe41544d4ee5
Revises: eadb19694a58
Create Date: 2022-06-29 15:01:41.078374

"""
from alembic import op
import sqlalchemy as sa

from api import SQL_INIT_FILE
from extras import get_inserts_from_files


# revision identifiers, used by Alembic.
revision = 'fe41544d4ee5'
down_revision = 'eadb19694a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    departments_table = op.create_table('departments',
    sa.Column('IDDepartment', sa.Integer(), nullable=False),
    sa.Column('DepartmentName', sa.String(length=60), nullable=False),
    sa.Column('Boss', sa.String(length=60), nullable=False),
    sa.Column('Phone', sa.BigInteger(), nullable=False),
    sa.Column('OfficeDean', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('IDDepartment')
    )
    # ### end Alembic commands ###
    inserts = get_inserts_from_files(SQL_INIT_FILE)
    op.bulk_insert(
        departments_table,
        inserts[departments_table.name]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
